# https://goreleaser.com/customization/project/
project_name: fake-kli

# https://goreleaser.com/customization/release/
release:
  draft: true
  prerelease: auto
  name_template: "Konstellation CLI {{.Version}}"
  github:
    owner: keyrm10
    name: fake-kli

# https://goreleaser.com/customization/hooks/
before:
  hooks:
    - go mod tidy
    - go mod download

# https://goreleaser.com/customization/builds/
builds:
  - <<: &build_defaults
      binary: bin/kli
      main: ./cmd/main.go
      env:
        - GO111MODULE=on
        - CGO_ENABLED=0
      ldflags:
        - -s -w -X github.com/konstellation-io/kli/internal/build.Version={{.Version}}
        - -X github.com/konstellation-io/kli/internal/build.Date={{time "2006-01-02"}}
  - <<: *build_defaults
    id: macos
    goos: [darwin]
    goarch: [amd64, arm64]
  - <<: *build_defaults
    id: linux
    goos: [linux]
    goarch: [amd64, arm64]
  - <<: *build_defaults
    id: windows
    goos: [windows]
    goarch: [amd64, arm64]

# https://goreleaser.com/customization/archive/
archives:
  - <<: &archive_defaults
      name_template: "{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
      files:
        - LICENSE
      rlcp: true
      wrap_in_directory: false
  - <<: *archive_defaults
    id: nix
    builds: [macos, linux]
    format: tar.gz
  - <<: *archive_defaults
    id: windows-tar
    builds: [windows]
    format: tar.gz
  - <<: *archive_defaults
    id: windows-zip
    builds: [windows]
    format: zip

# https://goreleaser.com/customization/nfpm/
nfpms:
  - license: MIT
    maintainer: Konstellation
    homepage: https://github.com/konstellation-io/kli
    description: CLI tool to manage Konstellation
    dependencies:
      - go
    formats:
      - deb
      - rpm

# https://goreleaser.com/customization/checksum/
checksum:
  name_template: "{{ .ProjectName }}_v{{ .Version }}_SHA256SUMS"